set curl response of backend as last test

diff --git a/.github/workflows/e2e-tests.yaml b/.github/workflows/e2e-tests.yaml
--- a/.github/workflows/e2e-tests.yaml
+++ b/.github/workflows/e2e-tests.yaml
@@ -52,17 +52,6 @@ jobs:
         run: |
           ls -la
           docker compose -f docker-compose.yml up -d
-      -
-        name: Check curl response of backend
-        run: |
-          # wait till the fill-db-with-test-input finished writing to db
-          sleep 30
-          docker container ls
-          response_code=$(curl -o /dev/null -w "%{http_code}" http://127.0.0.1:5000/get_all_challenges/)
-          if [ "$response_code" -ne 200 ]; then
-            echo "Response code is not 200. Failing the pipeline."
-            exit 1
-          fi
       - name: Start frontend
         working-directory: ./frontend-svelte
         run: npm run dev &
@@ -84,6 +73,15 @@ jobs:
       -
         name: Check curl response of backend
         run: |
+          # wait till the fill-db-with-test-input finished writing to db
+          sleep 15
+          docker container ls
+          response_code=$(curl -o /dev/null -w "%{http_code}" http://127.0.0.1:5000/get_all_challenges/)
+          if [ "$response_code" -ne 200 ]; then
+            echo "Response code is not 200. Failing the pipeline."
+            exit 1
+          fi
+
           echo "start testing elo endpoints"
           response_code=$(curl -X POST http://127.0.0.1:5000/get_next_challenge -H "Content-Type: application/json" -d '{"user_id": "d037ce8d-0381-471f-bfa5-98467685a335"}')
           next_challenge=$(echo "$response_code" | grep "next_challenge")
